# 一行最多 120 字符
printWidth: 120
# 缩进字节数, 默认为4
tabWidth: 2
# 不使用缩进符，而使用空格
useTabs: false
# 行尾需要有分号
semi: true
# 使用单引号
singleQuote: true
# 对象的 key 仅在必要时用引号
quoteProps: as-needed
# 大括号内的首尾需要空格
bracketSpacing: true
endOfLine: lf

# html中对每个属性进行自动换行
singleAttributePerLine: true
htmlWhitespaceSensitivity: ignore
newlineBeforeReturn: true
newlineAfterReturn: true

arrowFunctionIndent: preserve

arrowParens: avoid

operatorLinebreak: after
